targets:
  $default:
    builders:
      riverpod_generator:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*
            - test/integration/**/*
      freezed:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/integration/*
            - test/integration/**/*
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - "type=lint"
builders:
  riverpod_generator:
    import: "package:riverpod_generator/builder.dart"
    builder_factories: ["riverpodBuilder"]
    build_extensions:
      ".dart": [".riverpod.g.part"]
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  go_router_builder:
    import: "package:go_router_builder/go_router_builder.dart"
    builder_factories: ["goRouterBuilder"]
    build_extensions:
      ".dart": ["go_router.g.part"]
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  freezed:
    import: "package:freezed/builder.dart"
    builder_factories: ["freezed"]
    build_extensions:
      ".dart": [".freezed.dart"]
    auto_apply: dependents
    build_to: source
    runs_before: ["json_serializable|json_serializable"]
  bootstrap_autoloader_builder:
    import: "package:velvet_generator/src/builders/bootstrap_builder.dart"
    builder_factories: ["bootstrapAutoloaderBuilder"]
    build_extensions:
      "lib/$lib$": ["lib/bootstrap.velvet.dart"]
    auto_apply: root_package
    build_to: source
  autoloader_builder:
    target: ":velvet_annotation"
    import: "package:velvet_generator/src/builders/autoloader_builder.dart"
    builder_factories: ["autoloaderBuilder"]
    build_extensions:
      ".dart": [".velvet.dart"]
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
  config_autoloader_builder:
    import: "package:velvet_generator/src/builders/config_builder.dart"
    builder_factories: ["configAutoloaderBuilder"]
    build_extensions: { "lib/$lib$": ["lib/config.velvet.dart"] }
    auto_apply: root_package
    build_to: source
