name: velvet_generator
description: The code generator for the Velvet framework. It helps to automate some tasks as autoload, service binding, and more.
version: 0.0.1-dev.5
homepage: https://github.com/dedecube/velvet/tree/main/packages/velvet_generator

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  analyzer: ^6.4.1
  build: ^2.4.1
  build_config: ^1.1.1
  flutter:
    sdk: flutter
  merging_builder: ^0.2.7
  quote_buffer: ^0.2.6
  source_gen: ^1.5.0
  velvet_annotation: ^0.0.1-dev.4
  velvet_support: ^0.0.1-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mandatory dependencies for make custom_lint work in monorepo
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  pyramid_lint: ^2.0.0
  riverpod_lint: ^2.3.10
  velvet_custom_lints: ^0.0.1-dev.1

topics:
  - code-generation
  - framework
