name: velvet
repository: https://github.com/dedecube/velvet
sdkPath: .fvm/flutter_sdk

command:
  version:
    hooks:
      pre: |
        npx vscode-generate-index-standalone packages/velvet_framework/lib/
        cd ./packages/velvet_framework && dart pub run build_runner build --delete-conflicting-outputs

packages:
  - examples/*
  - packages/*
  - plugins/*
