name: velvet_workspace

environment:
  sdk: ">=3.2.6 <4.0.0"

dev_dependencies:  
  melos: ^6.0.0
  
  # Lint related dependencies
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  pyramid_lint: ^2.0.0
  riverpod_lint: ^2.3.10

dependencies:
  flutter:
    sdk: flutter

flutter:
