name: velvet_cli
description: The CLI tool for the Velvet projects. It will help to speed up the development process.
version: 0.0.1-dev.1
homepage: https://github.com/dedecube/velvet/tree/main/packages/velvet_cli

environment:
  sdk: ">=3.2.6 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  yaml: ^3.1.0
  velvet_support: ^0.0.1-dev.8
  get_it: ^7.7.0
  dcli: ^6.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  velvet_cli: velvet_cli
