name: velvet_cli
description: A sample command-line application.
version: 0.0.1-dev-0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.2.6 <4.0.0"

# Add regular dependencies here.
dependencies:
  path: ^1.8.0
  yaml: ^3.1.0
  velvet_support: ^0.0.1-dev.7
  get_it: ^7.7.0
  dcli: ^6.0.5

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  velvet_cli: velvet_cli
