name: velvet_lints
description: Recommended lints for Flutter apps, packages, and plugins to encourage good coding practices.
version: 0.0.1-dev.2
homepage: https://github.com/dedecube/velvet/tree/main/packages/velvet_lints

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  pyramid_lint: ^2.0.0
  riverpod_lint: ^2.3.10
  # Code is not allowed in this package. Do not add any dependencies or dev_dependencies.

topics:
  - lints
