name: velvet_basic_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.0.0
  velvet_framework: ^0.0.1-dev.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  velvet_lints: ^0.0.1-dev.2

flutter:
  uses-material-design: true
