name: velvet_basic_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  velvet_annotation: ^0.0.1-dev.4
  velvet_framework: ^0.0.1-dev.10

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  velvet_generator: ^0.0.1-dev.5

  # Mandatory dependencies for make custom_lint work in monorepo
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  pyramid_lint: ^2.0.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
