name: velvet_basic_app
description: "A basic app that uses the Velvet Framework."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  velvet_framework: ^0.0.1-dev.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  velvet_lints: ^0.0.1-dev.0

flutter:
  uses-material-design: true
