name: velvet_annotation
description: "A package exposing annotations for velvel_generator. It is part of the Velvet framework."
version: 0.0.1-dev.1
homepage: "https://github.com/dedecube/velvet/tree/main/packages/velvet_annotation"

environment:
  sdk: ">=3.2.6 <4.0.0"
dev_dependencies:
   test: ^1.25.5

topics:
  - annotations
  - code-generation