name: velvet_annotation
description: "The annotations for the Velvet framework."
version: 0.0.1-dev.1
homepage: "https://github.com/dedecube/velvet/packages/velvet_annotation"

environment:
  sdk: ">=3.2.6 <4.0.0"
dev_dependencies:
   test: ^1.25.5
