name: velvet_annotation
description: "A package exposing annotations for velvel_generator. It is part of the Velvet framework."
version: 0.0.1-dev.4
homepage: "https://github.com/dedecube/velvet/tree/main/packages/velvet_annotation"

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  riverpod: ^2.5.1

dev_dependencies:
  test: ^1.25.5

topics:
  - annotations
  - code-generation