name: velvet_framework
description: "A framework for building Flutter applications based on Riverpod and GoRouter."
version: 0.0.1-dev.1
homepage: "https://github.com/dedecube/velvet/packages/velvet_framework"

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  color_shade: ^1.0.1
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_i18n: ^0.35.1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.0.2
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  shared_preferences: ^2.2.3
  talker_flutter: ^4.2.3
  talker_riverpod_logger: ^1.0.0
  theme_tailor_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.6.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  theme_tailor: ^3.0.1

flutter: null
