// GENERATED CODE. DO NOT MODIFY. Generated by ConfigAutoloaderGenerator.

// Autoloaded config providers.
import 'package:velvet_annotation/velvet_annotation.dart';
import './config/translation_config.dart';
import 'package:velvet_framework/translation/providers/translation_config_provider.dart';
import './config/theme_config.dart';
import 'package:velvet_framework/theme/providers/theme_config_provider.dart';
import './config/router_config.dart';
import 'package:velvet_framework/router/providers/router_config_provider.dart';
import './config/dev_inspector_config.dart';
import 'package:velvet_framework/dev_inspector/providers/dev_inspector_config_provider.dart';

final List<ConfigBinder> configProviders = [
  ConfigBinder(
    abstract: translationConfigProvider,
    concrete: (ref) => TranslationConfig(),
  ),
  ConfigBinder(
    abstract: themeConfigProvider,
    concrete: (ref) => ThemeConfig(),
  ),
  ConfigBinder(
    abstract: routerConfigProvider,
    concrete: (ref) => RouterConfig(),
  ),
  ConfigBinder(
    abstract: devInspectorConfigProvider,
    concrete: (ref) => DevInspectorConfig(),
  ),
];

// End of autoloaded config providers.
