// GENERATED CODE. DO NOT MODIFY. Generated by ConfigAutoloaderGenerator.

// Autoloaded config providers.
// ignore: depend_on_referenced_packages
import 'package:riverpod/riverpod.dart';
import './config/translation_config.dart';
import 'package:velvet_framework/translation/providers/translation_config_provider.dart';
import './config/router_config.dart';
import 'package:velvet_framework/router/providers/router_config_provider.dart';
import './config/dev_inspector_config.dart';
import 'package:velvet_framework/dev_inspector/providers/dev_inspector_config_provider.dart';

typedef ConfigCreate<T, R extends Ref> = T Function(R ref);

class ConfigBinder {
  ConfigBinder({required this.abstract, required this.concrete});

  final Provider abstract;
  final ConfigCreate concrete;
}

final List<ConfigBinder> configProviders = [
  ConfigBinder(
    abstract: translationConfigProvider,
    concrete: (ref) => TranslationConfig(),
  ),
  ConfigBinder(
    abstract: routerConfigProvider,
    concrete: (ref) => RouterConfig(),
  ),
  ConfigBinder(
    abstract: devInspectorConfigProvider,
    concrete: (ref) => DevInspectorConfig(),
  ),
];

// End of autoloaded config providers.
