name: velvet_support
description: "Provide support classes for the everyday work. Porting of some Laravel utilities to Dart."
version: 0.0.1-dev.1
homepage: "https://github.com/dedecube/velvet/packages/velvet_support"


environment:
  sdk: ">=3.2.6 <4.0.0"

dev_dependencies:
  test: ^1.25.5