name: velvet_support
description: Provide support classes for the everyday work. Porting of some Laravel utilities to Dart.
version: 0.0.1-dev.5
homepage: "https://github.com/dedecube/velvet/tree/main/packages/velvet_support"

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mandatory dependencies for make custom_lint work in monorepo
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  pyramid_lint: ^2.0.0
  riverpod_lint: ^2.3.10
  velvet_custom_lints: ^0.0.1-dev.4

dependency_overrides:
  meta: ^1.14.0

topics:
  - dart
  - support
  - utilities
  - laravel-porting
