// GENERATED CODE. DO NOT MODIFY. Generated by BootstrapAutoloaderGenerator.

// Autoloaded bootstrap functions.
import 'dart:async';
// ignore: depend_on_referenced_packages
import 'package:riverpod/riverpod.dart';

typedef BootstrapCreate<T, R extends Ref> = T Function(R ref);

final List<BootstrapCreate<FutureOr, FutureProviderRef>> bootstrapFunctions =
    [];

// End of autoloaded bootstrap functions
