name: Changelog to Discord

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      markdown_file:
        description: "Path to the markdown file"
        required: true
        default: "CHANGELOG.md"

jobs:
  extract_and_send:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && contains(github.event.head_commit.message, 'chore(release)')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send first section to Discord
        uses: ./.github/actions/extract-and-send
        with:
          filepath: CHANGELOG.md
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
